### ISSUE TITLE
Исправить документацию

### ISSUE THREAD

**Issue by AIexandrKotov** [SunSerega/PascalABC.Net-BlockFileOfT#3]
Я изменил документацию в твоём модуле, переведя её на более читабельный язык. 
В некоторых местах оставил дополнения в качестве комментариев.

[BlockFileOfT.zip](https://github.com/SunSerega/PascalABC.Net-BlockFileOfT/files/2742171/BlockFileOfT.zip)

**Comment by SunSerega** [comment]
Вообще так не хорошо, надо локально выкладывать описание issue.
