### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [SunSerega/PascalABC.Net-BlockFileOfT#5]
Cleanup code from the similar things:
![image](https://user-images.githubusercontent.com/42812113/65416673-13cc4b00-de01-11e9-8df3-6a7937f591a3.png)

![image](https://user-images.githubusercontent.com/42812113/65416576-df588f00-de00-11e9-915c-332b9ef95e5d.png)

**Comment by SunSerega** [comment]
Первое уже убрано. Второе надо.

И "similar" тут не подходит по значению.

**Comment by EmilyGraceSeville7cf** [comment]
Under similar i meant all commented code peaces.

**Comment by SunSerega** [comment]
А чем тебе не понравилось наличие комментов в коде?

Первый кусок кода был потому что он, возможно, ещё понадобился бы. Но теперь я переделал `TestForRefT` и убрал использование `GCHandle`, поэтому теперь такая проверка точно не нужна.

А второй - явно показывает что, в отличии от предыдущего метода - в данном не надо `.Refresh`.
Это кривота реализации .Net -а, инфу о которой я случайно глазом зацепил на msdn. Я могу в будущем забыть про это и добавить назад `.Refresh`, подумав что он там нужен, если там не будет этого коммента.

---

И - опять. "under", так же как то "similar", это топорный перевод. Вместо "under" должно быть "by".
В случае с "similar" сложнее. Там всё предложение криво составлено.
Слушай больше как говорят американцы и англичане чтоб понимать такие моменты.
