### ISSUE TITLE
Replace MessageBox with the exception throwing

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [SunSerega/PascalABC.Net-BlockFileOfT#6]
![image](https://user-images.githubusercontent.com/42812113/65416830-5d1c9a80-de01-11e9-86e9-155a840c5ca6.png)

**Comment by SunSerega** [comment]
Ты копаешься в старой версии. Смотри тут:
https://github.com/SunSerega/PascalABC.Net-BlockFileOfT/tree/master/LibSource

Если хочешь по быстрому засунуть новую версию модуля в стандартные модули - используй файлы из корня репозитория, в таком порядке:
1. CompileAndTest.exe
2. CopyToPF.bat
